name: Deploy to GitHub Pages

main:
git add .github/workflows/deploy.yml
git commit -m "Add deployment workflow"
git push origin main

on:
  push:
    branches: [main] # Trigger on pushes to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build static site
        run: npm run generate # Generates static files in `dist/`

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages # Creates a branch for built files
